### ISSUE TITLE
Tripped up by a comment

### ISSUE THREAD

**Issue by laxamar** [prewk/xml-string-streamer#53]
The parser is tripped up by comments (PHP 7.0)

A comment in the stream seems to have tripped up the parser.

`<!-- dates are now skipped, as opposed to being listed as 9999-12-31 -->`

`PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in /web/medianet/medianet.php on line 44
PHP Warning:  simplexml_load_string():  dates are now skipped, as opposed to being listed as 9999-12-31 --> in /web/medianet/medianet.php on line 44
PHP Warning:  simplexml_load_string():  ^ in /web/medianet/medianet.php on line 44
PHP Fatal error:  Uncaught Error: Call to a member function children() on boolean in /web/medianet/medianet.php:53
Stack trace:
#0 {main}
  thrown in /web/medianet/medianet.php on line 53`

**Comment by prewk** [comment]
Hi!

Can you provide some example XML that causes the problem? As far as I can see from your error message you're having a problem with invalid XML, that may or may not be the parser's fault.

It's supposed to support XML comments, though. I seem to only have a unit test for the `StringWalker` parser, though: https://github.com/prewk/xml-string-streamer/blob/master/tests/unit/XmlStringStreamer/Parser/StringWalkerTest.php#L160

**Comment by laxamar** [comment]
It is a 700+MB file, and trips in the middle, so took me a while to get the EXACT line that trips it - I was relying on my debug echos .... I managed to get the exact line

The issue seems related to tags INSIDE comments that trips something:
`<!-- Reminder: Since 1.6, Missing <ACTION-From> dates are now skipped, as opposed to being listed as 9999-12-31 -->`

In context (if you need it)

`<Metadata-Item>
        <Id>1533681686</Id>
        <Comp-Id>412022613</Comp-Id>
        <Metadata-Type-Id>57</Metadata-Type-Id>
        <Metadata-Value>7540344</Metadata-Value>
        <Created-Date>2017-04-18</Created-Date>
        <Last-Updated-Date>2017-04-18</Last-Updated-Date>
    </Metadata-Item>
</Metadata>


<Component-Actions><Component-Action>
        <Comp-Id>403542725</Comp-Id>
        <Published-Date>9999-12-31</Published-Date>
        <Last-Updated-Date>2016-11-28</Last-Updated-Date>
    </Component-Action>`

Should will create a small complete file with test data and just the suspect lines?

**Comment by laxamar** [comment]
Demo code and file:

[xml-comment-fail.zip](https://github.com/prewk/xml-string-streamer/files/975262/xml-comment-fail.zip)

**Comment by prewk** [comment]
Ah, `StringWalker` has an "expectGT" option for this very thing, actually. It's `false` by default due to the extra logic it takes to check for it, and it's pretty rare. See:


| Option | Default | Description |
| ------ | ------- | ----------- |
| (int) captureDepth | `2` | Depth we start collecting nodes at |
| (array) tags | See example | Supported tags |
| (bool) expectGT | `false` | Whether to support `>` in XML comments/CDATA or not |
| (array) tagsWithAllowedGT | See example | If _expectGT_ is `true`, this option lists the tags with allowed `>` characters in them |

I could run your example when adding `"expectGT" => true` to the `$options`. Test if that works for you on the large XML as well.

**Comment by laxamar** [comment]
UGH

RTFM next time :-)

Thanks

**Comment by laxamar** [comment]
Actually, the really large file fails now for memory reasons. The xml file is one giant object with millions of objects inside (not my idea).

`<Label-Owner>
        <Id>1524</Id>
        <Corp-Code>TRM</Corp-Code>
        <Label-Owner-Name>Toolroom Records</Label-Owner-Name>
        <Active-Status-Code>A</Active-Status-Code>
        <Created-Date>2014-06-27</Created-Date>
        <Last-Updated-Date>2016-12-12</Last-Updated-Date>
    </Label-Owner>
</Label-Owners>PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65011736 bytes) in /web/medianet/vendor/prewk/xml-string-streamer/src/XmlStringStreamer/Parser/StringWalker.php on line 249
`
This is no longer related to the main subject - suggestions? Open other issue?

**Comment by laxamar** [comment]
Wrong on size ..
`rw-r--r--. 1 medianet_cron medianet_cron  67G May  2 14:08 BOTWW-FULL-Thu-Apr-20-00-35-08-PST-2017-A-2.xml`

**Comment by prewk** [comment]
Yeah okay, your problem is probably that you're catching too much, in that case. The library is made for capturing just certain nodes, and with the `StringWalker` you're able to specify at which depth those nodes are (whatever they are) with the `captureDepth` option.

If you always want to capture the same-named nodes and no duplicates of that name appear you can try using the `UniqueNode` parser instead (with the `"uniqueNode" => "MyNode"` option).
