### ISSUE TITLE
Entity: line 2: parser error : Premature end of data in tag ..

### ISSUE THREAD

**Issue by tuttiflirty** [prewk/xml-string-streamer#69]
I have tag with CDATA such as:
`<training><![CDATA[<p>English for experts.</p>]]></training>`
but an error is thrown as it contains html tags. 

For instance `<![CDATA[English for experts.]]>` works well.

I tried to set up options like:
```
$options = array(
            "captureDepth" => 3,
            "tagsWithAllowedGT" => array("training"),
            "expectGT" => true
        );
```

but it didn't help neither.

Any suggestions pls ?

**Comment by prewk** [comment]
Weird, the expectGT should solve it. Can't test until after the weekend. Can you post some small XML document that reproduce the error meanwhile?

**Comment by prewk** [comment]
Btw, you can simply just try the other Parser as well (UniqueNode, see readme). It doesn't even look at the CDATA.

**Comment by AmitLekhi1990** [comment]
Hi prewk,

Does uniqueNode also parse CDATA?

It gives me an empty SimpleXmlElement for the below.

`<short_description>
<![CDATA[ Testing the xml string parser ]]>
</short_description>`

**Comment by prewk** [comment]
Can you get the string for the same xml manually with SimpleXML without xml-string-streamer?

Because it sounds like you're missing the cast: https://stackoverflow.com/questions/2970602/php-how-to-handle-cdata-with-simplexmlelement

The uniqueNode parser doesn't really "parse" anything, it just searches for the next occurrence.

**Comment by AmitLekhi1990** [comment]
Cast works....Thanks!
