### ISSUE TITLE
Ability to Parse from String instead of file

### ISSUE THREAD

**Issue by mlhkr** [prewk/xml-string-streamer#72]
Hi,
I'm reading getting XML with curl and need to load it via XmlStringStreamer as string not a file but couldn't find a way.

**Comment by prewk** [comment]
Hi,

You must _stream_ with curl for it to make sense to use this library, are you doing that? Because if you're just fetching a big XML somewhere with curl normally and save it in a variable as a string, you've already spent the memory this library is supposed to help you _not spend_.

The out-of-box solution this library provides for the problem "stream a large XML from somewhere on the internet" is this package: https://github.com/prewk/xml-string-streamer-guzzle

If you still need to use your own custom curl solution you'll have to learn how to stream via a file handle, a quick google shows this SO answer: https://stackoverflow.com/questions/1342583/manipulate-a-string-that-is-30-million-characters-long/1342760#1342760

Good luck!
